# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2 as _descriptor_pb2
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

_file_descriptor_proto = _descriptor_pb2.FileDescriptorProto()
_file_descriptor_proto.name = 'remote.proto'
_file_descriptor_proto.package = 'prometheus'
_file_descriptor_proto.syntax = 'proto3'

_write_request = _file_descriptor_proto.message_type.add()
_write_request.name = 'WriteRequest'
_timeseries_field = _write_request.field.add()
_timeseries_field.name = 'timeseries'
_timeseries_field.number = 1
_timeseries_field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_REPEATED
_timeseries_field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
_timeseries_field.type_name = '.prometheus.TimeSeries'

_time_series = _file_descriptor_proto.message_type.add()
_time_series.name = 'TimeSeries'
_labels_field = _time_series.field.add()
_labels_field.name = 'labels'
_labels_field.number = 1
_labels_field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_REPEATED
_labels_field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
_labels_field.type_name = '.prometheus.Label'
_samples_field = _time_series.field.add()
_samples_field.name = 'samples'
_samples_field.number = 2
_samples_field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_REPEATED
_samples_field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
_samples_field.type_name = '.prometheus.Sample'

_label = _file_descriptor_proto.message_type.add()
_label.name = 'Label'
_name_field = _label.field.add()
_name_field.name = 'name'
_name_field.number = 1
_name_field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
_name_field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_STRING
_value_field = _label.field.add()
_value_field.name = 'value'
_value_field.number = 2
_value_field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
_value_field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_STRING

_sample = _file_descriptor_proto.message_type.add()
_sample.name = 'Sample'
_sample_value_field = _sample.field.add()
_sample_value_field.name = 'value'
_sample_value_field.number = 1
_sample_value_field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
_sample_value_field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_DOUBLE
_sample_timestamp_field = _sample.field.add()
_sample_timestamp_field.name = 'timestamp'
_sample_timestamp_field.number = 2
_sample_timestamp_field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
_sample_timestamp_field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_INT64

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    _file_descriptor_proto.SerializeToString()
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remote_pb2', globals())
